### ISSUE TITLE
update rack-openid to 1.4

### ISSUE THREAD

**Issue by swills** [omniauth/omniauth-openid#23]
Is there a reason to stick the pessimistic version constraint on rack-openid or a reason to stick to 1.3.x? If not, perhaps you could change it to >= 1.3.1 or ~> 1.3? Would be nice for those who want to use the latest version. Thanks!

**Comment by shioyama** [comment]
Second this, there are issues such as [this one](https://github.com/grosser/rack-openid/pull/4) that have been fixed in later versions and it would be great to get those included.

**Comment by tmilewski** [comment]
`rack-openid` is now `~> 1.4.0`
