### ISSUE TITLE
some example with Rails app?

### ISSUE THREAD

**Issue by nmenag** [omniauth/omniauth-openid#34]

**Comment by krtschmr** [comment]
did you get it working so far?

**Comment by nmenag** [comment]
Yes, i'm working with an integration with keycloak server and a Rails app.

**Comment by eugyev** [comment]
do you have a link to the example?

**Comment by nmenag** [comment]
@eugyev  I actually have this in the Gemfile: 

```ruby
gem 'devise', '~> 4.4'
gem 'omniauth', '~> 1.1'
gem 'pundit', '~> 1.1'
gem 'simple_token_authentication', '~> 1.15', '>= 1.15.1'
gem 'openid_connect', '~> 1.0'
```
create a strategy class the same code of gem.

**Comment by febincloudyuga** [comment]
@nmenag - I'm working on integrating it with Keycloak for our application. Would you be having an example of how to go about it?

**Comment by vinaykp3** [comment]
Can you please provide the working example with rails and keycloak integration.
